#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: net service Centos
  include: net_centos.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"

- name: net services Ubuntu
  include: net_ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
