#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: install components ubuntu
  apt: name={{ item }} state=present
  with_items:
   - isc-dhcp-server

- name: configure isc-dhcp-server
  template: src=../templates/dhcpd.conf dest=/etc/dhcp/dhcpd.conf

- name: restart isc-dhcp-server service
  command: /usr/sbin/service isc-dhcp-server restart
